---
title: "Trainging Stack Overview"
author: "Rion Dooley"
date: "9/19/2018"
output: html_document
---

# Training Stack Overview

The tutorial environment you will use is comprised of a handful of well known open source technologies. We have integrated and preconfigured them into a cohesive containerized deployment that can be run in our Jetstream Cloud infrastructure as well as locally on your machine using Docker. If you are attending the training in person, you will be given access to your own hosted instance of the training environment complete with vanity DNS and training account. If you are following along after the fact, see the section on "Following along at home" for instructions on standing up the training stack locally.  

The following sections touch on the different technologies included in the training environment.

## RStudio

RStudio is a web-based IDE for the R language.  to create and share documents that contain live code, equations, visualizations and explanatory text. Uses include: data cleaning and transformation, numerical simulation, statistical modeling, machine learning and much more.

[Website](http://rstudio.com/).

We will be using a RStudio server as the primary web interface for this workshop. Several notebooks have been provided to you, in advance, to guide you through the workshop. After the workshop, you may use the [Agave RStudio image](https://hub.docker.com/r/agaveplatform/RStudio-notebook/) to recreate the notebook server and repeat the workshop, or continue on with your own work at your leisure.  

The Agave image has several customizations to facilitate use of the platform and ease much of the heavy lifting done behind the scenes in this tutorial.

#### Custom Kernels

Your RStudio server has multiple languages available for use within R markdown cells right away. We have preconfigured them with several useful libraries and tools to help users get up and running with common tasks easier. Additionally, we have bundled in Agave CLI and Python & R SDK into the container and preconfigured them for the tutorial tenant. Each kernel is pre-authenticated with valid Agave auth tokens that you can use to begin interacting with the Agave Platform right away.

#### Shared file system

The `$HOME/work` directory within your RStudio server is shared with your sandbox, so you can safely copy data between the two environments quickly and easily.

#### Web console  

RStudio contains a web terminal that can be used to access your sandbox environment or interact with the RStudio container itself. To login to your sandbox from the RStudio web terminal, simply run the following command:  

```
ssh sandbox
```  

#### Tutorial notebooks  

This tutorial is presented as a series of RStudio notebooks. If you are attending this tutorial in person, you will download the notebooks into the home directory of your notebook server. If you are following along after the fact, you should download the notebooks from the github repository into your RStudio workspace.

```
git clone --depth 1 https://github.com/agavetraining/gateways18
``` 

#### API access  

The tutorial walks you through the process of obtaining a set of API keys an authenticating to the Agave Platform. Once this is done, you no longer need to authenticate to follow the tutorial. Both the Agave CLI, R, and Python SDK will be picked up your authorization cache and automatically refresh it as needed.

#### Extras

Inside of the `examples` directory, you will find several notebooks to help you learn more about the Agave platform, containers, and SciOps. We leave these for you to follow after the tutorial.


## Shiny  

[Shiny](http://shiny.rstudio.com/) is an R package that makes it easy to build interactive web apps straight from R. You can host standalone apps on a webpage or embed them in R Markdown documents or build dashboards. We have bundled Shiny support into your RStudio image for use within the tutorial.    

> The bundled Shiny server is not a production-ready instance. Do not use this in production environments!

## Plumber

[Plumber](https://www.rplumber.io/) is an R package that converts your existing R code to a web API using a decorators in your source code. Unlike Shiny, no additional hosting environment is needed, and syntax should be familiar to anyone who has written a REST service in another language. A dedicated Plumber server has been deployed as part of your training stack to host the APIs written for the Plumber section of the tutorial. The container is more than sufficient for training and light traffic and may serve you well for your own personal use. See the section on Publishing and Production for considerations when pushing Plumber to production.

## OpenCPU  

[OpenCPU](https://www.opencpu.org/) is a system for embedded scientific computing and reproducible research. The OpenCPU server provides a reliable and interoperable HTTP API for data analysis based on R. You can either use the public servers or host your own as we do within your training stack. OpenCPU is a bit heavier solution than Plumber, but comes capable of supporting a much heaver load than Plumber. The instance of OpenCPU running in your stack is preconfigured with the OpenCPU tutorial services. See the section on Publishing and Production for considerations when deploying OpenCPU to production.

## Sandbox
The tutorial sandbox is an Ubuntu 16.04 server running as a Docker container on a VM dedicated for your use in this tutorial. The sandbox has a standard HPC build environment with OpenMPI, Python 2, Python 3, build-essential, gfortran, openssl, git, jq, vim, and a host of other utilities.

#### Container runtimes
Docker and Singularity are both pre-installed in your Sandbox. All images used in this tutorial are available from the public Agave Docker Hub and Singularity Hub accounts. You may also use your own private registry accounts. You will need to login to the respective registries on your own.

#### Funwave example code
The sample code for this project is already present in $HOME/FUNWAVE-TVD.

#### Shared file system
The `$HOME/work` directory within your sandbox is shared with your RStudio server, so you can safely copy data between the two environments quickly and easily.

#### Accessibility
To login to the sandbox from outside the RStudio server, use the host IP address. You will find the public IP address of your sandbox in the $VM_IPADDRESS environment variable. Valid ssh keys are available in the `~/.ssh` director of your RStudio server.

Alternatively, you can append your own public key to the $HOME/.ssh/authorized_keys file and login using your own private key.

```
# on a normal linux system, this will be located in your local 
# $HOME/.ssh/id_rsa.pub file. Copy the contents to your clipboard
cat $HOME/.ssh/id_rsa.pub
```  

This will output something like the following:

```
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAAAgQC7yAdpv9WC2qM9wDyEE6nuvlliDdlOX2PaRh71aZ7/6qCn+dfkhp0wPNZLZ8iveh3gh8X6iEHiWaM+mSOlUKsj4WVixfQ6+WmMdIz1myAcMGWpCWTMACnfW4w65TCwbSQlF28D+pnPuWKRrGWtx3ttF9pQDu4lUlo4ldBvq8XfPQ== foo@example.com
``` 

Now append the outputted value to the `$HOME/.ssh/authorized_keys` file in the sandbox. To do this from the RStudio UI by up your `authorized_keys` file in the text editor. Remember to save the file when you are done.

To append your public key from your RStudio terminal, update the value of `YOUR_PUBLIC_KEY_VALUE` in the following code block and paste it into your RStudio terminal.

Note: If you do not have a terminal open, you can open one up by clicking on this link.

```
# update the next line with your own public key
YOUR_PUBLIC_KEY_VALUE=<paste the contents of your own public key file here>

# now we will append the key to the end of the authorized_keys file in the sandbox. 
# Make sure you run the entire code block in your RStudio terminal otherwise an empty
# value will be appended to your authorized_keys file.
echo "$YOUR_PUBLIC_KEY_VALUE" >>  $HOME/.ssh/authorized_keys
```  

Once you have updated your authorized_keys file, you should be able to login to your sandbox from the outside world using port 10022. To generate the ssh login command, update the following command with the path to your own private key file and run it from your RStudio terminal.

```
echo "ssh -i $HOME/.ssh/id_rsa.pem -p 10022 jovyan@$VM_IPADDRESS"
You may also run it from within a RStudio notebook cell by prefxing a ! to the command.

!echo "ssh -i $HOME/.ssh/id_rsa.pem -p 10022 jovyan@$VM_IPADDRESS"
```

> _Note: If you are running the training stack locally, you should substitute localhost for $VM_IPADDRESS in the above command.

#### Persistence
Your VM will remain available for 1-2 days following the tutorial. During that time, your data will remain available. After that, the VM an any data saved with it will be destroyed. If you need to persist your data, it is recommended that you move it to another host, or create your own account in the Agave Platform and save your data in the free cloud storage provied to you by default there.


# Logging In

We have already configured resources for you to use in this tutorial. 

#### Virtual Machine

Each of you have a dedicated VM provided by the [Jetstream Cloud](https://jetstream-cloud.org/). You will use this VM for the duration of the tutorial. 

#### Training Account

A training account on the Agave Platform has also been allocated to you.

#### Login

Your RStudio server is available at: 
> `<username>.gateways18.training.agaveplatform.org`. 

Your Plumber services are available at:  
> `<username>.gateways18.training.agaveplatform.org/plumber/<path>/<to>/<service>`.

Your OpenCPU server is available at:  
> `<username>.gateways18.training.agaveplatform.org/opencpu`. 

Usernames will be training001 to training025. We will count off to determine our instance.

When you first login, you will find it empty, save for a notebook named [INSTALL.Rmd](INSTALL.Rmd). Open this notebook by clicking on the notebook name in the files tab on the right side of the page. Once open, click the *"run"* button and select *"Run all"*. This will fetch all the tutorial notebooks from the tutorial's git repository an add them to your workspace. 

Once complete, open the [02 - Data Science Intro](02-data-science-intro.nb.Rmd) notebook to being the meat of our tutorial.
 

# Following along at home

If you are following along with this tutorial at home, you can recreate the tutorial RStudio server and sandbox environments by running the containers on your own server using the [Docker Compose file](docker-compose.yml)

To run the above, you need to first set the environment variables `AGAVE_USERNAME`, `AGAVE_PASSWORD`, and `NGROK_TOKEN`. The first two should be your agave username and password as obtained from [the Agave registration page](https://sandbox.agaveplatform.org/create_account). The ngrok token should be obtained from [ngrok](https://ngrok.com)

Ngrok will provide tunnelling for you so that Agave can ssh into your laptop or desktop machine. It will do this by setting the `VM_IPADDRESS`, `VM_HOSTNAME` and `VM_SSH_PORT` for you.

Once you have these things setup, you should be able to run `docker-compose up -d` (note: you should run this command from the base directory of this repository.) You should then be able use your browser to connect to the tutorial setup on port 80 of your Docker host. If you are running Docker for Mac, Docker for Windows, or Docker CE on Linux, your address should be: (http://localhost).

