version: '2'

volumes:
  training-volume:
  ssh-keygen-volume:
  jenkins-home-volume:

services:

  # traefik reverse proxy to expose the jupyter and jenkins servers over ssl via a common hostname
  traefik:
    image: traefik:latest
    mem_limit: 512m
    command: --debug=True --docker --docker.watch --web --web.address=:28443 --entryPoints='Name:http Address::80 --entryPoints='Name:https Address::443 --defaultEntryPoints='http,https'
    ports:
      - '443:443'
      - '80:80'
      - '28443:28443'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  # This is a single shot container that creates a set of ssh keys per instance
  # and deploys them to a persistent volume shared between the sandbox and
  # jupyter container. By doing this, we don't need to ship keys with the image
  # or source.
  ssh-keygen:
    image: agaveplatform/rstudio:3.4.3-shiny
    entrypoint: /bin/bash
    command: /usr/local/bin/ssh-keygen/keygen.sh
    environment:
      - "ROOT=TRUE"
      - "USER=${AGAVE_USERNAME}"
      - "PASSWORD=${AGAVE_PASSWORD}"
      - "AGAVE_USERNAME=${AGAVE_USERNAME}"
      - "AGAVE_PASSWORD=${AGAVE_PASSWORD}"
      - "AGAVE_TENANT=${AGAVE_TENANT}"
      - "AGAVE_CACHE_DIR=/home/${AGAVE_USERNAME}/work/.agave"
      - "S6_KEEP_ENV=1"
    env_file:
      - training.env
    volumes:
      - "ssh-keygen-volume:/home/${AGAVE_USERNAME}/.ssh"
      - "./docker/ssh-keygen:/usr/local/bin/ssh-keygen"

  rstudio:
    build:
      context: .
      dockerfile: docker/rstudio/Dockerfile
    image: agaveplatform/rstudio:3.4.3-shiny
    mem_limit: 2048m
    restart: on-failure
    ports:
      - '8787:8787'
      - '9101-10:9101-10'
      - '9200-10:9200-10'
    depends_on:
      - ssh-keygen
    env_file:
      - training.env
    environment:
      - "ROOT=TRUE"
      - "USER=${AGAVE_USERNAME}"
      - "PASSWORD=${AGAVE_PASSWORD}"
      - "AGAVE_CACHE_DIR=/home/${AGAVE_USERNAME}/work/.agave"
      - "AGAVE_TENANT_BASE_URL=https://sandbox.agaveplatform.org"
      - "AGAVE_BASE_URL=https://sandbox.agaveplatform.org"
      - "S6_KEEP_ENV=1"
      - "SHINY_CONNECT_USERNAME=${SHINY_CONNECT_USERNAME}"
      - "SHINY_CONNECT_TOKEN=${SHINY_CONNECT_TOKEN}"
      - "SHINY_CONNECT_SECRET=${SHINY_CONNECT_SECRET}"
    volumes:
      - "ssh-keygen-volume:/home/$AGAVE_USERNAME/.ssh"
      - "training-volume:/home/$AGAVE_USERNAME/work"
      - ".:/home/$AGAVE_USERNAME/notebooks"
      - "./INSTALL.Rmd:/home/$AGAVE_USERNAME/INSTALL.Rmd"
    labels:
      - "traefik.port=8787"
      - "traefik.protocol=http"
      - "traefik.tags=$AGAVE_USERNAME,rstudio"
      - "traefik.backend=$AGAVE_USERNAME-training-rstudio"
      - "traefik.frontend.rule=PathPrefix:/"

  plumber:
    build:
      context: .
      dockerfile: docker/plumber/Dockerfile
    image: agaveplatform/plumber
  sandbox:
    image: agaveplatform/training-sandbox:latest
    mem_limit: 2048m
    privileged: True
    restart: on-failure
    ports:
      - '10022:22'
    depends_on:
      - ssh-keygen
    env_file:
      - training.env
    environment:
      - VM_MACHINE=$$ENVIRONMENT-node-$$AGAVE_USERNAME
    volumes:
      - ssh-keygen-volume:/home/jovyan/.ssh
      - training-volume:/home/jovyan/work
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - traefik.enable=false

  opencpu:
    build:
      context: .
      dockerfile: docker/opencpu/Dockerfile
    image: agaveplatform/opencpu:latest
    mem_limit: 1024m
    restart: on-failure
    ports:
      - '8004:8004'
    depends_on:
      - ssh-keygen
    env_file:
      - training.env
    environment:
      - "AGAVE_TENANT_BASE_URL=https://sandbox.agaveplatform.org"
      - "AGAVE_BASE_URL=https://sandbox.agaveplatform.org"
      - "BOOTSTRAP_AGAVE_CLIENT=1"
    volumes:
      - training-volume:/home/opencpu/work
#      - "./opencpu/tutorial:/home/opencpu/tutorial"
    labels:
      - "traefik.port=8004"
      - "traefik.protocol=http"
      - "traefik.tags=$AGAVE_USERNAME,opencpu"
      - "traefik.backend=$AGAVE_USERNAME-training-opencpu"
      - "traefik.frontend.rule=PathPrefix:/ocpu"


#  jenkins:
#    build:
#      context: jenkins
#      dockerfile: Dockerfile
#    image: agaveplatform/jenkins:sc18
#    mem_limit: 2048m
#    privileged: True
#    restart: on-failure
#    ports:
#      - '8080:8080'
#      - '8443:8443'
#    depends_on:
#      - ssh-keygen
#    env_file:
#      - training.env
#    environment:
#      - AGAVE_CACHE_DIR=/var/jenkins_home/.$AGAVE_TENANT
##      - JENKINS_OPTS="--prefix=/jenkins "
#    volumes:
#      - ssh-keygen-volume:/var/jenkins_home/.ssh
##      - jenkins-home-volume:/var/jenkins_home
#    labels:
#      - "traefik.port=8080"
#      - "traefik.protocol=http"
#      - "traefik.tags=jenkins"
#      - "traefik.backend=jenkins"
#      - "traefik.frontend.rule=PathPrefix:/jenkins"
#      - "traefik.frontend.passHostHeader=true"
